version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - 3050:80
  tianart-frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./tianart-frontend
    volumes:
      - /app/node_modules
      - ./tianart-frontend:/app
